-- Create the CATEGORIES table
CREATE TABLE CATEGORIES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

-- Create the BOOKS table with a foreign key constraint
CREATE TABLE BOOKS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    AUTHOR VARCHAR(255),
    PRICE INT,
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);
